/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coffeeHouse;


/**
 *
 * @author slvai_000
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */

    public MainFrame() {
        initComponents();
        buttonGroup1.add(espressoRadio);
        buttonGroup1.add(houseBlendRadio);
        buttonGroup1.add(darkRoastRadio);
        buttonGroup1.add(decafRadio);
        espressoRadio.setSelected(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content o
     *
     *
     * f this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        espressoRadio = new javax.swing.JRadioButton();
        houseBlendRadio = new javax.swing.JRadioButton();
        darkRoastRadio = new javax.swing.JRadioButton();
        decafRadio = new javax.swing.JRadioButton();
        mochaBox = new javax.swing.JCheckBox();
        soyBox = new javax.swing.JCheckBox();
        whipBox = new javax.swing.JCheckBox();
        steamedMilkBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Coffee:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 27, -1, -1));

        jLabel2.setText("Cost:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 88, -1, -1));

        jLabel3.setText(" ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 390, -1));

        jLabel4.setText(" ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 88, 80, -1));

        jButton1.setText("Make coffee");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 274, -1, 38));

        jLabel5.setText("Ingredients:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

        espressoRadio.setText("Espresso (1.99)");
        jPanel1.add(espressoRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 137, -1, -1));

        houseBlendRadio.setText("HouseBlend (.89)");
        jPanel1.add(houseBlendRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 167, -1, -1));

        darkRoastRadio.setText("Dark Roast (.99)");
        jPanel1.add(darkRoastRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 197, -1, -1));

        decafRadio.setText("Decaf (1.05)");
        jPanel1.add(decafRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 227, -1, -1));

        mochaBox.setText("Mocha (.20)");
        jPanel1.add(mochaBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));

        soyBox.setText("Soy (.15)");
        jPanel1.add(soyBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, -1, -1));

        whipBox.setText("Whip (.10)");
        jPanel1.add(whipBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, -1, -1));

        steamedMilkBox.setText("Steamed Milk (.10)");
        jPanel1.add(steamedMilkBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Beverage beverage = null;
        if (espressoRadio.isSelected()) {
            beverage = new Espresso();
        }
        if (houseBlendRadio.isSelected()) {
            beverage = new HouseBlend();
        }
        if (darkRoastRadio.isSelected()) {
            beverage = new DarkRoast();
        }
        if (decafRadio.isSelected()) {
            beverage = new Decaf();
        }

        if (beverage != null) {
            if (soyBox.isSelected()) {
                beverage = new Soy(beverage);
            }
            if (whipBox.isSelected()) {
                beverage = new Whip(beverage);
            }
            if (mochaBox.isSelected()) {
                beverage = new Mocha(beverage);
            }
            if (steamedMilkBox.isSelected()) {
                beverage = new SteamedMilk(beverage);
            }
            jLabel3.setText(beverage.getDescription());
            jLabel4.setText(String.format("%.2f", (beverage.cost())));
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton darkRoastRadio;
    private javax.swing.JRadioButton decafRadio;
    private javax.swing.JRadioButton espressoRadio;
    private javax.swing.JRadioButton houseBlendRadio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox mochaBox;
    private javax.swing.JCheckBox soyBox;
    private javax.swing.JCheckBox steamedMilkBox;
    private javax.swing.JCheckBox whipBox;
    // End of variables declaration//GEN-END:variables
}
